// all need attend contestant
const varAllContestants = [
  {
    id: 0,
    username: 'dhucstmaster',
    name: '主持人',
    logged: false,
    score: 0,
    out: false,
  },
  {
    id: 1,
    username: '2171793',
    name: '马永东',
    logged: false,
    score: 0,
    out: false,
    isPlayer: true,
  },
  {
    id: 2,
    username: '161310405',
    name: '樊静宜',
    logged: false,
    score: 0,
    out: false,
    isPlayer: true,
  },
  {
    id: 3,
    username: '2171784',
    name: '龙勰',
    logged: false,
    score: 0,
    out: false,
    isPlayer: true,
  },
  {
    id: 4,
    username: '151320116',
    name: '任方成',
    logged: false,
    score: 0,
    out: false,
    isPlayer: false,
  },
  {
    id: 5,
    username: '151330122',
    name: '杨博',
    logged: false,
    score: 0,
    out: false,
    isPlayer: false,
  },
  {
    id: 6,
    username: '151330111',
    name: '李曾贤',
    logged: false,
    score: 0,
    out: false,
    isPlayer: false,
  },
  {
    id: 7,
    username: '141310218',
    name: '姜威',
    logged: false,
    score: 0,
    out: false,
    isPlayer: false,
  },
  {
    id: 8,
    username: '10105275',
    name: '黄老师',
    logged: false,
    score: 0,
    out: false,
    isPlayer: false,
  },
  {
    id: 9,
    username: '2171800',
    name: '刘欣怡',
    logged: false,
    score: 0,
    out: false,
    isPlayer: false,
  },
  {
    id: 10,
    username: '151320222',
    name: '哈哈哈',
    logged: false,
    score: 0,
    out: false,
    isPlayer: false,
  },
  {
    id: 11,
    username: '161310414',
    name: '马希磊',
    logged: false,
    score: 0,
    out: false,
    isPlayer: false,
  },
];

module.exports = varAllContestants;