// all need attend contestant
const varAllContestants = [
  {
    id: 0,
    username: 'dhucstmaster',
    name: '主持人',
    logged: false,
    score: 0,
    out: false,
  },
  {
    id: 1,
    username: '141320105',
    name: '孙琳',
    logged: false,
    score: 0,
    out: false,
    isPlayer: true,
  },
  {
    id: 2,
    username: '2171741',
    name: '张天',
    logged: false,
    score: 0,
    out: false,
    isPlayer: true,
  },
  {
    id: 3,
    username: '2171783',
    name: '顾欣',
    logged: false,
    score: 0,
    out: false,
    isPlayer: true,
  },
  {
    id: 4,
    username: '2171784',
    name: '龙勰',
    logged: false,
    score: 0,
    out: false,
    isPlayer: true,
  },
  {
    id: 5,
    username: '161310318',
    name: '朱经纬',
    logged: false,
    score: 0,
    out: false,
    isPlayer: true,
  },
  {
    id: 6,
    username: '161310119',
    name: '梁雄飞',
    logged: false,
    score: 0,
    out: false,
    isPlayer: true,
  },
  {
    id: 7,
    username: '161310311',
    name: '戴顺新',
    logged: false,
    score: 0,
    out: false,
    isPlayer: false,
  },
  {
    id: 8,
    username: '161310505',
    name: '牛童',
    logged: false,
    score: 0,
    out: false,
    isPlayer: false,
  },
  {
    id: 9,
    username: '161310414',
    name: '马希磊',
    logged: false,
    score: 0,
    out: false,
    isPlayer: false,
  },
  {
    id: 10,
    username: '151330122',
    name: '杨博',
    logged: false,
    score: 0,
    out: false,
    isPlayer: false,
  },
  {
    id: 11,
    username: '151330111',
    name: '李曾贤',
    logged: false,
    score: 0,
    out: false,
    isPlayer: false,
  },
  {
    id: 12,
    username: '141310218',
    name: '姜威',
    logged: false,
    score: 0,
    out: false,
    isPlayer: false,
  },
  {
    id: 13,
    username: '10105275',
    name: '黄老师',
    logged: false,
    score: 0,
    out: false,
    isPlayer: false,
  },
  {
    id: 14,
    username: '2171800',
    name: '刘欣怡',
    logged: false,
    score: 0,
    out: false,
    isPlayer: false,
  },
  {
    id: 15,
    username: '141310110',
    name: '张艺凡',
    logged: false,
    score: 0,
    out: false,
    isPlayer: false,
  },
  {
    id: 16,
    username: 'FatherMrc',
    name: 'My Son',
    logged: false,
    score: 0,
    out: false,
    isPlayer: false,
  },
  {
    id: 17,
    username: '151340224',
    name: '张洛彬',
    logged: false,
    score: 0,
    out: false,
    isPlayer: false,
  },
];

module.exports = varAllContestants;